name: Cleanup
on: repository_dispatch
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Remove Artifacts
      if: github.event.action == 'delete_all_artifacts'
      uses: christian-korneck/delete-run-artifacts-action@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        parent_runid: ${{ github.event.client_payload.parent_runid }}
        parent_repo: ${{ github.event.client_payload.parent_repo }}
